# Configuration file for Calamares - abzOS 1.0
---
modules-search: [ local, /usr/lib/calamares/modules, /usr/lib/x86_64-linux-gnu/calamares/modules ]

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - dpkg-unsafe-io
  - sources-media
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - grubcfg
  - bootloader
  - packages
  - luksbootkeyfile
  - plymouthcfg
  - initramfscfg
  - initramfs
  - dpkg-unsafe-io-undo
  - sources-media-unmount
  - sources-final
  - umount

- show:
  - finished

branding: abzos
prompt-install: false
dont-chroot: false
