---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux"
img: "/boot/initramfs-linux.img"
fallback: "/boot/vmlinuz-linux"
fallbackImg: "/boot/initramfs-linux.img"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEpoxyConfig: true
