FROM abzos-debian:1.0
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    xserver-xorg \
    xinit \
    x11-xserver-utils \
    xfonts-base \
    fonts-dejavu-core \
    dbus-user-session \
    polkitd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target
RUN ln -sf /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service

RUN (id abzos &>/dev/null || useradd -m -s /bin/bash -u 1000 abzos) && \
    echo "abzos:abzos" | chpasswd && \
    echo "root:toor" | chpasswd && \
    usermod -aG sudo,adm,audio,video,plugdev,cdrom,netdev abzos 2>/dev/null || true
